name: sync-gitee
on:
  push:
    branches:
      - master

jobs:
  sync-gitee:
    name: Sync to Gitee
    runs-on: ubuntu-latest
    environment: gitee

    steps:
      - name: Sync to Gitee
        uses: abersheeran/sync-gitee-mirror@v1-beta
        with:
          repository: qstxdy/newSSE
          username: ${{ secrets.GITEE_USERNAME }}
          password: ${{ secrets.GITEE_PASSWORD }}